# This is a basic workflow to help you get started with Actions

name: lang_0

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    continue-on-error: true
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        bug_ind: [1, 2, 3, 4, 5]#, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          sudo apt update
          sudo apt-get install gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat maven

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.34'

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout d4j
        uses: actions/checkout@v2
        with:
          repository: amir9979/defects4j
          path: .
          fetch-depth: 0
      
      - run: cpanm --installdeps .
      - run: ./init.sh

      - name: initialize-project-and-collect-issues
        run: ./initialize-project-and-collect-issues.pl -p Lang -n commons-lang -w bug-mining -r https://github.com/apache/commons-lang.git -g jira -t LANG -e "/(LANG-\d+)/mi"
        working-directory: ./framework/bug-mining
      
      
      - name: initialize-revisions
        run: ./initialize-revisions.pl -p Lang -w bug-mining_${{ matrix.bug_ind }}  -i ${{ matrix.bug_ind }} 
        working-directory: ./framework/bug-mining

      - name: analyze-project
        run: ./analyze-project.pl -p Lang -w bug-mining_${{ matrix.bug_ind }}  -g jira -t LANG -i ${{ matrix.bug_ind }} 
        working-directory: ./framework/bug-mining


      - name: get-trigger
        run: ./get-trigger.pl -p Lang -w bug-mining_${{ matrix.bug_ind }}
        working-directory: ./framework/bug-mining

      - name: get-metadata
        run: ./get-metadata.pl -p Lang -w bug-mining_${{ matrix.bug_ind }}
        working-directory: ./framework/bug-mining


      
      - name: Upload bug-mining
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: bug-mining
          # A file, directory or wildcard pattern that describes what to upload
          path: ./framework/bug-mining


