# This is a basic workflow to help you get started with Actions

name: lang_0

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # continue-on-error: true
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        bug_ind: [19] #[19, 28, 29, 45, 49, 83, 224, 229, 259, 262, 284, 21, 27, 30, 31, 32, 33, 34, 36, 48, 54, 56, 57, 68, 72, 73, 76, 78, 87, 90, 176, 178, 181, 182, 183, 200, 219, 225, 230, 248, 249, 252, 258, 267, 269, 275, 279, 282, 283, 289, 290, 291, 296, 305, 306, 307, 309, 311, 312, 314, 315, 317, 319, 321, 325]



    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          sudo apt update
          sudo apt-get install gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat maven

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.34'

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install junitparser
          pip install networkx
          pip install pytest 
          pip install gitpython
          pip install jira
          pip install termcolor 
          pip install openpyxl  
          pip install javalang
          pip install pathlib
          pip install junitparser
          pip install numpy
          pip install sklearn
          pip install pandas
          pip install pyswarm
          pip install networkx
          pip install lizard
          pip install jsons


      - name: Checkout d4j
        uses: actions/checkout@v2
        with:
          repository: amir9979/defects4j
          path: .
          fetch-depth: 0
      
      - name: Checkout javadiff
        uses: actions/checkout@v2
        with:
          repository: amir9979/javadiff
          path: ./framework/bug-mining/tracing/javadiff
          fetch-depth: 0

      - name: Checkout sfl
        uses: actions/checkout@v2
        with:
          repository: amir9979/sfl
          path: ./framework/bug-mining/tracing/sfl
          fetch-depth: 0

      - run: cpanm --installdeps .
      - run: ./init.sh

      - name: execute
        run: python wrapper.py commons-lang bug-mining_${{ matrix.bug_ind }} ${{ matrix.bug_ind }}
        working-directory: ./framework/bug-mining

      - name: delete repo
        if: ${{always()}}
        run: |
            rm -rf ./framework/bug-mining/bug-mining_${{ matrix.bug_ind}}/project_repos
            rm -rf ./framework/bug-mining/bug-mining_${{ matrix.bug_ind}}/issues
            rm -rf ./framework/bug-mining/bug-mining_${{ matrix.bug_ind}}/framework/core
            rm -rf ./framework/bug-mining/bug-mining_${{ matrix.bug_ind}}/gitlog
            rm -rf ./framework/bug-mining/bug-mining_${{ matrix.bug_ind}}/issues.txt
            rm -rf ./framework/bug-mining/bug-mining_${{ matrix.bug_ind}}/framework/projects/Lang/lib
            rm -rf ./framework/bug-mining/tracing
      
      - name: Upload bug-mining
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: bug-mining
          # A file, directory or wildcard pattern that describes what to upload
          path: ./framework/bug-mining
